// <auto-generated />
using System;
using Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entidades.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201023213103_TerceraMigracion")]
    partial class TerceraMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidades.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("CarreraIdCarrera")
                        .HasColumnType("int");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdAlumno");

                    b.HasIndex("CarreraIdCarrera");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Entidades.Asignatura", b =>
                {
                    b.Property<int>("IdAsignatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarreraIdCarrera")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int>("Comision")
                        .HasColumnType("int");

                    b.Property<int>("Horario")
                        .HasColumnType("int");

                    b.Property<int>("NombreAsignatura")
                        .HasColumnName("Nombre")
                        .HasColumnType("int");

                    b.Property<int?>("NotaIdNotas")
                        .HasColumnType("int");

                    b.HasKey("IdAsignatura");

                    b.HasIndex("CarreraIdCarrera");

                    b.HasIndex("NotaIdNotas");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("Entidades.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Facultad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("Entidades.Notas", b =>
                {
                    b.Property<int>("IdNotas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Final")
                        .HasColumnType("real")
                        .HasMaxLength(2);

                    b.Property<float>("PrimerParcial")
                        .HasColumnType("real")
                        .HasMaxLength(2);

                    b.Property<float>("PrimerRecuperatorio")
                        .HasColumnType("real")
                        .HasMaxLength(2);

                    b.Property<float>("SegundoParcial")
                        .HasColumnType("real")
                        .HasMaxLength(2);

                    b.Property<float>("SegundoRecuperatorio")
                        .HasColumnType("real")
                        .HasMaxLength(2);

                    b.HasKey("IdNotas");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("Entidades.Staff", b =>
                {
                    b.Property<int>("IdStaff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdStaff");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Entidades.Alumno", b =>
                {
                    b.HasOne("Entidades.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraIdCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entidades.Asignatura", b =>
                {
                    b.HasOne("Entidades.Carrera", null)
                        .WithMany("Materias")
                        .HasForeignKey("CarreraIdCarrera");

                    b.HasOne("Entidades.Notas", "Nota")
                        .WithMany()
                        .HasForeignKey("NotaIdNotas");
                });
#pragma warning restore 612, 618
        }
    }
}
