// <auto-generated />
using System;
using Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entidades.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidades.Alumno", b =>
                {
                    b.Property<int>("idAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CarreraidTitulo")
                        .HasColumnType("int");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAlumno");

                    b.HasIndex("CarreraidTitulo");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Entidades.Asignatura", b =>
                {
                    b.Property<int>("idAsignatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarreraidTitulo")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int>("Comision")
                        .HasColumnType("int");

                    b.Property<int>("Horario")
                        .HasColumnType("int");

                    b.Property<int>("NombreAsignatura")
                        .HasColumnType("int");

                    b.Property<int?>("NotaidNotas")
                        .HasColumnType("int");

                    b.HasKey("idAsignatura");

                    b.HasIndex("CarreraidTitulo");

                    b.HasIndex("NotaidNotas");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("Entidades.Carrera", b =>
                {
                    b.Property<int>("idTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Facultad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTitulo");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("Entidades.Notas", b =>
                {
                    b.Property<int>("idNotas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Final")
                        .HasColumnType("real");

                    b.Property<float>("PrimerParcial")
                        .HasColumnType("real");

                    b.Property<float>("PrimerRecuperatorio")
                        .HasColumnType("real");

                    b.Property<float>("SegundoParcial")
                        .HasColumnType("real");

                    b.Property<float>("SegundoRecuperatorio")
                        .HasColumnType("real");

                    b.HasKey("idNotas");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("Entidades.Staff", b =>
                {
                    b.Property<int>("idStaff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idStaff");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Entidades.Alumno", b =>
                {
                    b.HasOne("Entidades.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraidTitulo");
                });

            modelBuilder.Entity("Entidades.Asignatura", b =>
                {
                    b.HasOne("Entidades.Carrera", null)
                        .WithMany("Materias")
                        .HasForeignKey("CarreraidTitulo");

                    b.HasOne("Entidades.Notas", "Nota")
                        .WithMany()
                        .HasForeignKey("NotaidNotas");
                });
#pragma warning restore 612, 618
        }
    }
}
